### ISSUE TITLE
File overwriting Fix

### ISSUE THREAD

**Issue by cbelizon** [ezze/ezze-elfinder#3]
I found a bug on elFinderVolumeDriver.class.php line 1375 when you try to overwrite a file. 

The fix:

Change the line 1375 with:

$this->remove($test);

My best regards! :)

**Comment by ezze** [comment]
How do you overwrite a file? A tried to copy and paste a file with the same name from one directory to another, and after confirmation dialog everything succeeds. Tested on Ubuntu 12.04 LTS, PHP 5.3.10.

**Comment by cbelizon** [comment]
If yout try to drag and drop one file to the navigator with the same filename of already existing file you will see the problem.

Tested on Windows 7 PHP 5.2.6

I would suggest you to update the entire Yii widget package with the last elfinder version v2.x. You can get it here:

https://github.com/nao-pon/elFinder-nightly

Indeed, I already realized that my bugfix was solved long time ago :)

**Comment by ezze** [comment]
Thanks a lot, man!

I got it. It's in `upload` method. I compared with [actual code](https://github.com/Studio-42/elFinder/blob/2.x/php/elFinderVolumeDriver.class.php#L1414) of ElFinder and found this issue solved in the same  way like yours. :)

The latter release on [ElFinder](http://elfinder.org) is still 2.0 and I think it's better to wait until new stable version will be released.

**Comment by cbelizon** [comment]
But the website seems that is not longer updated and outdated.

If you look the github wiki page, the owner recommend the use of v2.x. I've experimented problems with jQuery and jQuery UI versions that are built-in with Yii v1.1.13. Crop and Rotate images doesn't works with newest jQuery versions (even the versions included in Yii Core), this kind of issues are solved with 2.x branch.

Look at the official wiki. This monday I have to work with your plugin and I'm going to test with the lattest version, I'll tell you if version 2.x is not compatible with your wrapper.

Glad to help!

**Comment by ezze** [comment]
As I can see one should take changes from `2.1` branch due to everything from `2.x` has been merged there. However, only further testing could show how stable this version is. I guess it's not supposed as stable yet and new commits will come most likely.

Anyway, let me know whether you had luck with this one. And thank you so much again.
